deploymentMode: SingleBinary

loki:
  auth_enabled: false

singleBinary:
  replicas: 1

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

gateway:
  enabled: false

minio:
  enabled: false