apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flask-staging
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/seethalakshmii/TASK-4.git
    targetRevision: HEAD
    path: k8s/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true