apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: flask-app
  namespace: staging

spec:
  replicas: 2

  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
      - name: flask-app

        image: seetha88/flask-app:v2

        ports:
        - containerPort: 5000

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

  strategy:
    canary:
      steps:
      - setWeight: 50

      - pause:
          duration: 30s

      - setWeight: 100