apiVersion: v1
kind: Service

metadata:
  name: flask-app
  namespace: staging
  labels:
    app: flask-app

spec:
  selector:
    app: flask-app

  ports:
  - name: http
    port: 80
    targetPort: 5000