apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: flask-app-staging
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: flask-app

  namespaceSelector:
    matchNames:
    - staging

  endpoints:
  - port: http
    path: /metrics
    interval: 15s