apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flask-production
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/seethalakshmii/TASK-4.git
    targetRevision: main   # IMPORTANT: use stable branch for prod
    path: k8s/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true